//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWONE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ViewPsits
    {
        public int Id { get; set; }
        public Nullable<int> Id_Number { get; set; }
        public string Name { get; set; }
        public string Course { get; set; }
        public Nullable<int> Event_Id { get; set; }
        public string Event_Name { get; set; }
        public Nullable<System.DateTime> Event_Date { get; set; }
    }
}
