//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWONE.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBSysProjEntities2 : DbContext
    {
        public DBSysProjEntities2()
            : base("name=DBSysProjEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<PSITS> PSITS { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<VW_ADMIN3> VW_ADMIN3 { get; set; }
        public virtual DbSet<vw_ViewAdmin1> vw_ViewAdmin1 { get; set; }
        public virtual DbSet<VW_PSITS4> VW_PSITS4 { get; set; }
    
        public virtual int sp_DeletePsits(Nullable<int> pId)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeletePsits", pIdParameter);
        }
    
        public virtual int sp_DeleteStudent(Nullable<int> sId)
        {
            var sIdParameter = sId.HasValue ?
                new ObjectParameter("sId", sId) :
                new ObjectParameter("sId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteStudent", sIdParameter);
        }
    }
}
