//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWONE.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PSITS4
    {
        public int studentID { get; set; }
        public string STUDENTs_Name { get; set; }
        public string COURSE { get; set; }
        public string EventName { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
    }
}
